/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package main

import (
	"github.com/golang/protobuf/proto"
)

type TestStruct8Item struct {
	SubKey int32
	__data StructZZ
	__root *TestStruct8
}

func NewTestStruct8Item(subKey int32, root *TestStruct8) *TestStruct8Item {
	return &TestStruct8Item{
		SubKey: subKey,
		__root: root,
	}
}

func (this *TestStruct8Item) Get(mutable bool) *StructZZ {
	if mutable {
		this.__root.__dirtyData[this.SubKey] = 1
	}
	return &this.__data
}

func (this *TestStruct8Item) Unmarshal(data []byte) error {
	if err := proto.Unmarshal(data, &this.__data); err != nil {
		return err
	}
	return nil
}

func (this *TestStruct8Item) Marshal() ([]byte, error) {
	data, err := proto.Marshal(&this.__data)
	if err != nil {
		return nil, err
	}
	return data, nil
}
