/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package main

import "encoding/json"

type TestStruct2Item struct {
	SubKey int
	myb    bool
	myf1   float32
	myf2   float64
	myi0   int
	myi1   int8
	myi2   int16
	myi3   int32
	myi4   int64
	myi5   uint
	myi6   uint8
	myi7   uint16
	myi8   uint32
	myi9   uint64
	mys1   string
	mys2   []byte

	__root *TestStruct2
}

func NewTestStruct2Item(subKey int, root *TestStruct2) *TestStruct2Item {
	return &TestStruct2Item{
		SubKey: subKey,
		__root: root,
	}
}

func (this *TestStruct2Item) GetMyb() bool {
	return this.myb
}

func (this *TestStruct2Item) GetMyf1() float32 {
	return this.myf1
}

func (this *TestStruct2Item) GetMyf2() float64 {
	return this.myf2
}

func (this *TestStruct2Item) GetMyi0() int {
	return this.myi0
}

func (this *TestStruct2Item) GetMyi1() int8 {
	return this.myi1
}

func (this *TestStruct2Item) GetMyi2() int16 {
	return this.myi2
}

func (this *TestStruct2Item) GetMyi3() int32 {
	return this.myi3
}

func (this *TestStruct2Item) GetMyi4() int64 {
	return this.myi4
}

func (this *TestStruct2Item) GetMyi5() uint {
	return this.myi5
}

func (this *TestStruct2Item) GetMyi6() uint8 {
	return this.myi6
}

func (this *TestStruct2Item) GetMyi7() uint16 {
	return this.myi7
}

func (this *TestStruct2Item) GetMyi8() uint32 {
	return this.myi8
}

func (this *TestStruct2Item) GetMyi9() uint64 {
	return this.myi9
}

func (this *TestStruct2Item) GetMys1() string {
	return this.mys1
}

func (this *TestStruct2Item) GetMys2() []byte {
	return this.mys2
}

func (this *TestStruct2Item) SetMyb(value bool) {
	this.myb = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyf1(value float32) {
	this.myf1 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyf2(value float64) {
	this.myf2 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi0(value int) {
	this.myi0 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi1(value int8) {
	this.myi1 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi2(value int16) {
	this.myi2 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi3(value int32) {
	this.myi3 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi4(value int64) {
	this.myi4 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi5(value uint) {
	this.myi5 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi6(value uint8) {
	this.myi6 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi7(value uint16) {
	this.myi7 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi8(value uint32) {
	this.myi8 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMyi9(value uint64) {
	this.myi9 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMys1(value string) {
	this.mys1 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) SetMys2(value []byte) {
	this.mys2 = value
	this.__root.__dirtyData[this.SubKey] = 1
}

func (this *TestStruct2Item) Unmarshal(data []byte) error {
	var temp struct {
		Myb  bool    `json:"myb"`
		Myf1 float32 `json:"myf1"`
		Myf2 float64 `json:"myf2"`
		Myi0 int     `json:"myi0"`
		Myi1 int8    `json:"myi1"`
		Myi2 int16   `json:"myi2"`
		Myi3 int32   `json:"myi3"`
		Myi4 int64   `json:"myi4"`
		Myi5 uint    `json:"myi5"`
		Myi6 uint8   `json:"myi6"`
		Myi7 uint16  `json:"myi7"`
		Myi8 uint32  `json:"myi8"`
		Myi9 uint64  `json:"myi9"`
		Mys1 string  `json:"mys1"`
		Mys2 []byte  `json:"mys2"`
	}
	err := json.Unmarshal(data, &temp)
	if err != nil {
		return err
	}
	this.myb = temp.Myb
	this.myf1 = temp.Myf1
	this.myf2 = temp.Myf2
	this.myi0 = temp.Myi0
	this.myi1 = temp.Myi1
	this.myi2 = temp.Myi2
	this.myi3 = temp.Myi3
	this.myi4 = temp.Myi4
	this.myi5 = temp.Myi5
	this.myi6 = temp.Myi6
	this.myi7 = temp.Myi7
	this.myi8 = temp.Myi8
	this.myi9 = temp.Myi9
	this.mys1 = temp.Mys1
	this.mys2 = temp.Mys2
	return nil
}

func (this *TestStruct2Item) Marshal() ([]byte, error) {
	var temp struct {
		Myb  bool    `json:"myb"`
		Myf1 float32 `json:"myf1"`
		Myf2 float64 `json:"myf2"`
		Myi0 int     `json:"myi0"`
		Myi1 int8    `json:"myi1"`
		Myi2 int16   `json:"myi2"`
		Myi3 int32   `json:"myi3"`
		Myi4 int64   `json:"myi4"`
		Myi5 uint    `json:"myi5"`
		Myi6 uint8   `json:"myi6"`
		Myi7 uint16  `json:"myi7"`
		Myi8 uint32  `json:"myi8"`
		Myi9 uint64  `json:"myi9"`
		Mys1 string  `json:"mys1"`
		Mys2 []byte  `json:"mys2"`
	}
	temp.Myb = this.myb
	temp.Myf1 = this.myf1
	temp.Myf2 = this.myf2
	temp.Myi0 = this.myi0
	temp.Myi1 = this.myi1
	temp.Myi2 = this.myi2
	temp.Myi3 = this.myi3
	temp.Myi4 = this.myi4
	temp.Myi5 = this.myi5
	temp.Myi6 = this.myi6
	temp.Myi7 = this.myi7
	temp.Myi8 = this.myi8
	temp.Myi9 = this.myi9
	temp.Mys1 = this.mys1
	temp.Mys2 = this.mys2
	return json.Marshal(temp)
}
