/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------

package main

import (
	go_redis_orm "github.com/fananchong/go-redis-orm.v2"
	"github.com/garyburd/redigo/redis"
)

type RD_TestStruct1 struct {
	Key  uint64
	myb  bool
	myf1 float32
	myf2 float64
	myi0 int
	myi1 int8
	myi2 int16
	myi3 int32
	myi4 int64
	myi5 uint
	myi6 uint8
	myi7 uint16
	myi8 uint32
	myi9 uint64
	mys1 string
	mys2 []byte

	__dirtyData map[string]interface{}
	__isLoad    bool
	__dbKey     string
}

func NewRD_TestStruct1() *RD_TestStruct1 {
	return &RD_TestStruct1{
		__dirtyData: make(map[string]interface{}),
	}
}

func (this *RD_TestStruct1) Load(dbName string, key uint64) error {
	if this.__isLoad == true {
		return errors.New("alreay load!")
	}
	this.__dbKey = dbKey(key)
	db := go_redis_orm.GetDB(dbName)
	val, err := db.Do("HGETALL", this.__dbKey)
	if err != nil {
		return err
	}
	if err := redis.ScanStruct(val, this); err != nil {
		return err
	}
	this.__isLoad = true
	return nil
}

func (this *RD_TestStruct1) Save(dbName string) error {
	if len(this.__dirtyData) == 0 {
		return nil
	}
	db := go_redis_orm.GetDB(dbName)
	if _, err := c.Do("HMSET", redis.Args{}.Add(this.__dbKey).AddFlat(this.__dirtyData)...); err != nil {
		return err
	}
	this.__dirtyData = make(map[string]interface{})
	return nil
}

func (this *RD_TestStruct1) Delete(dbName string) error {
	db := go_redis_orm.GetDB(dbName)
	_, err := db.Do("DEL", dbKey(key))
	return err
}

func (this *RD_TestStruct1) IsLoad() bool {
	return this.__isLoad
}

func (this *RD_TestStruct1) GetMyb() bool {
	return this.myb
}

func (this *RD_TestStruct1) GetMyf1() float32 {
	return this.myf1
}

func (this *RD_TestStruct1) GetMyf2() float64 {
	return this.myf2
}

func (this *RD_TestStruct1) GetMyi0() int {
	return this.myi0
}

func (this *RD_TestStruct1) GetMyi1() int8 {
	return this.myi1
}

func (this *RD_TestStruct1) GetMyi2() int16 {
	return this.myi2
}

func (this *RD_TestStruct1) GetMyi3() int32 {
	return this.myi3
}

func (this *RD_TestStruct1) GetMyi4() int64 {
	return this.myi4
}

func (this *RD_TestStruct1) GetMyi5() uint {
	return this.myi5
}

func (this *RD_TestStruct1) GetMyi6() uint8 {
	return this.myi6
}

func (this *RD_TestStruct1) GetMyi7() uint16 {
	return this.myi7
}

func (this *RD_TestStruct1) GetMyi8() uint32 {
	return this.myi8
}

func (this *RD_TestStruct1) GetMyi9() uint64 {
	return this.myi9
}

func (this *RD_TestStruct1) GetMys1() string {
	return this.mys1
}

func (this *RD_TestStruct1) GetMys2() []byte {
	return this.mys2
}
