package main

const template1nSubitem string = `/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package {{packagename}}

import (
	{{import_struct_format}}
)

// {{classname}}ItemData : 子对象所有字段
type {{classname}}ItemData struct {
	{{fields_def}}
}

// {{classname}}Item : 代表 1 个 redis 子对象
type {{classname}}Item struct {
	SubKey {{sub_key_type}}
	dataIn{{classname}}Item {{classname}}ItemData
	rootIn{{classname}}Item *{{classname}}
}

// New{{classname}}Item : New{{classname}}Item 的构造函数
func New{{classname}}Item(subKey {{sub_key_type}}, root *{{classname}}) *{{classname}}Item {
	return &{{classname}}Item{
		SubKey: subKey,
		rootIn{{classname}}Item: root,
	}
}

{{func_get1n}}

{{func_set1n}}

// Unmarshal : 反序列化方法
func (obj{{classname}}Item *{{classname}}Item) Unmarshal(data []byte) error {
	if err := {{struct_format}}.Unmarshal(data, &obj{{classname}}Item.dataIn{{classname}}Item); err != nil {
		return err
	}
	return nil
}

// Marshal : 序列化方法
func (obj{{classname}}Item *{{classname}}Item) Marshal() ([]byte, error) {
	data, err := {{struct_format}}.Marshal(&obj{{classname}}Item.dataIn{{classname}}Item)
	if err != nil {
		return nil, err
	}
	return data, nil
}
`

const get1nFuncString = `// Get{{field_name_upper}} : 获取字段值
func (obj{{classname}}Item *{{classname}}Item) Get{{field_name_upper}}() {{field_type}} {
	return obj{{classname}}Item.dataIn{{classname}}Item.{{field_name_upper}}
}`

const set1nFuncString = `// Set{{field_name_upper}} : 设置字段值
func (obj{{classname}}Item *{{classname}}Item) Set{{field_name_upper}}(value {{field_type}}) {
	obj{{classname}}Item.dataIn{{classname}}Item.{{field_name_upper}} = value
	obj{{classname}}Item.rootIn{{classname}}Item.dirtyDataIn{{classname}}[obj{{classname}}Item.SubKey] = 1
}`

const get1nFuncStringForStructFiled = `// Get{{field_name_upper}} : 获取字段值
func (obj{{classname}}Item *{{classname}}Item) Get{{field_name_upper}}(mutable bool) *{{field_type}} {
	if mutable {
		obj{{classname}}Item.rootIn{{classname}}Item.dirtyDataIn{{classname}}[obj{{classname}}Item.SubKey] = 1
	}
	return &obj{{classname}}Item.dataIn{{classname}}Item.{{field_name_upper}}
}`
