package main

const template1n_subitem2 string = `/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package {{packagename}}

import (
	{{import_struct_format}}
)

type {{classname}}Item struct {
	SubKey {{sub_key_type}}
	__data {{sub_item_type}}
	__root *{{classname}}
}

func New{{classname}}Item(subKey {{sub_key_type}}, root *{{classname}}) *{{classname}}Item {
	return &{{classname}}Item{
		SubKey: subKey,
		__root: root,
	}
}

func (this *{{classname}}Item) Get(mutable bool) *{{sub_item_type}}{
	if mutable {
		this.__root.__dirtyData[this.SubKey] = 1
	}
	return &this.__data
}


func (this *{{classname}}Item) Unmarshal(data []byte) error {
	if err := {{struct_format}}.Unmarshal(data, &this.__data); err != nil {
		return err
	}
	return nil
}

func (this *{{classname}}Item) Marshal() ([]byte, error) {
	data, err := {{struct_format}}.Marshal(&this.__data)
	if err != nil {
		return nil, err
	}
	return data, nil
}
`
