package main

const template1nSubitem2 string = `/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package {{packagename}}

import (
	{{import_struct_format}}
)

// {{classname}}Item : 代表 1 个 redis 子对象
type {{classname}}Item struct {
	SubKey {{sub_key_type}}
	dataIn{{classname}}Item {{sub_item_type}}
	rootIn{{classname}}Item *{{classname}}
}

// New{{classname}}Item : New{{classname}}Item 的构造函数
func New{{classname}}Item(subKey {{sub_key_type}}, root *{{classname}}) *{{classname}}Item {
	return &{{classname}}Item{
		SubKey: subKey,
		rootIn{{classname}}Item: root,
	}
}

// Get : 获取字段值
func (obj{{classname}}Item *{{classname}}Item) Get(mutable bool) *{{sub_item_type}}{
	if mutable {
		obj{{classname}}Item.rootIn{{classname}}Item.dirtyDataIn{{classname}}[obj{{classname}}Item.SubKey] = 1
	}
	return &obj{{classname}}Item.dataIn{{classname}}Item
}

// Unmarshal : 反序列化方法
func (obj{{classname}}Item *{{classname}}Item) Unmarshal(data []byte) error {
	if err := {{struct_format}}.Unmarshal(data, &obj{{classname}}Item.dataIn{{classname}}Item); err != nil {
		return err
	}
	return nil
}

// Marshal : 序列化方法
func (obj{{classname}}Item *{{classname}}Item) Marshal() ([]byte, error) {
	data, err := {{struct_format}}.Marshal(&obj{{classname}}Item.dataIn{{classname}}Item)
	if err != nil {
		return nil, err
	}
	return data, nil
}
`
