package main

const template1n_subitem string = `/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------
package {{packagename}}

import "encoding/json"

type {{classname}}Item struct {
	SubKey {{sub_key_type}}
	{{fields_def}}

	__root *{{classname}}
}

func New{{classname}}Item(subKey {{sub_key_type}}, root *{{classname}}) *{{classname}}Item {
	return &{{classname}}Item{
		SubKey: subKey,
		__root: root,
	}
}

{{func_get1n}}

{{func_set1n}}

func (this *{{classname}}Item) Unmarshal(data []byte) error {
	var temp struct {
		{{fields_def_json}}
	}
	err := json.Unmarshal(data, &temp)
	if err != nil {
		return err
	}
	{{set_this1n}}
	return nil
}

func (this *{{classname}}Item) Marshal() ([]byte, error) {
	var temp struct {
		{{fields_def_json}}
	}
	{{set_temp1n}}
	return json.Marshal(temp)
}
`

const get1nFuncString = `func (this *{{classname}}Item) Get{{field_name_upper}}() {{field_type}} {
	return this.{{field_name_lower}}
}`

const set1nFuncString = `func (this *{{classname}}Item) Set{{field_name_upper}}(value {{field_type}}) {
	this.{{field_name_lower}} = value
	this.__root.__dirtyData[this.SubKey] = 1
}`
